### ISSUE TITLE
Active/Selected Cells

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#104]
I propose that a cell should not have `active` or `selected` properties.  I suggest adding an attached property to cells for `selected`, and adding a `getSelectedCells()` method to the notebook model.

cc @jasongrout

**Comment by blink1073** [comment]
We already have the `activeCellIndex` for the `active` state.

**Comment by blink1073** [comment]
Actually, `select(cell)`, `deselect(cell)`, and `isSelected(cell)` would be required.

**Comment by jasongrout** [comment]
+1 to not having active or selected be intrinsic cell properties. Like the mode, those are properties of the container.
