### ISSUE TITLE
The big squeeze

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#11]
Publish 0.4, add a deprecation notice to the other repos, and update jupyter-js-editor?

**Comment by jasongrout** [comment]
Yep, thanks for the checklist.

**Comment by jasongrout** [comment]
0.4.1 is published.

**Comment by blink1073** [comment]
Okay, working on editor now.

**Comment by jasongrout** [comment]
@blink1073 - I think this is done now, right?

**Comment by blink1073** [comment]
This one needs a deprecation warning: https://github.com/jupyter/jupyter-js-editor

**Comment by jasongrout** [comment]
Done: https://www.npmjs.com/package/jupyter-js-editor

**Comment by blink1073** [comment]
Can you also update the text on the repo?

**Comment by blink1073** [comment]
I don't have access.

**Comment by jasongrout** [comment]
Sure. Good point. I updated the readme and package.json. I'll update the headline on the repo too.

**Comment by jasongrout** [comment]
better?

**Comment by blink1073** [comment]
We'll need to do the same for filebrowser, domutils, terminal, and docmanager.  I can do the README and npm if you take the headlines.

**Comment by jasongrout** [comment]
This issue is for the notebook big squeeze. I'm happy to do those things for the other big squeeze too, though.

**Comment by blink1073** [comment]
Yeah, I'll open one on jupyter-js-ui.

**Comment by jasongrout** [comment]
(see https://github.com/jupyter/jupyter-js-ui/issues/25 for the ui issue)
