### ISSUE TITLE
Executing a code cell should mark the notebook as dirty

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#117]

**Comment by minrk** [comment]
Seems like dirty should be handled in the notebook model. Any change to the notebook model (or its persisted subset) should trigger dirty. Executing a cell should do this indirectly by clearing output and prompt.

If the model is stored with something like immutable.js, it should be easy for the saving code to easily track 'is the current state what I last saved'

**Comment by blink1073** [comment]
Yes, the intent was to make this semantically part of the model.  I just quickly made the issue while I was working on another issue.  We are also considering moving `delete/undelete` and `copy/paste` to the model, since the undelete stack and copied cells could be considered state, what are your thoughts on that?

**Comment by minrk** [comment]
That's one thing where we want to be clear about treating "application" state and "document" state differently. copied data is logically application state (unless we can actually use the clipboard), but I wouldn't consider it document state.

**Comment by blink1073** [comment]
yes, the same could be said of `active` and `selected` state

**Comment by blink1073** [comment]
We could have a base model that is only for rendering, and then add these features on top.

**Comment by ellisonbg** [comment]
So far, we are more treating the model as a "view model" of sorts that has
some state that is view related. We could create a separate layer for the
actual document state, but we though that the amount of state for the view
was minimal enough that it wasn't worth it.

On Tue, Mar 22, 2016 at 6:04 AM, Steven Silvester notifications@github.com
wrote:

> We could have a base model that is only for rendering, and then add these
> features on top.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/issues/117#issuecomment-199803582

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
