### ISSUE TITLE
Docs don't build

### ISSUE THREAD

**Issue by bschwb** [jupyter/jupyter-js-notebook#118]
The docs at http://jupyter.org/jupyter-js-notebook/ are down, so I tried to build them myself and that didn't work either.
Here the npm log:
[npm-debug.log.txt](https://github.com/jupyter/jupyter-js-notebook/files/183737/npm-debug.log.txt)

**Comment by blink1073** [comment]
Hi @BerndSchwarzenbacher, unfortunately TypeDoc only works up to TypeScript 1.6 currently, and we are using string literal types, a TypeScript 1.8 feature.

**Comment by ellisonbg** [comment]
Ouch any timeframe on that situation improving?

**Comment by blink1073** [comment]
The author has gone dark for the past few months.  There is an alternate project, https://github.com/docscript/docscript, that is a WIP.

**Comment by sccolbert** [comment]
I've built a custom typedoc before to solve this issue when TS 1.6 was released. The typedoc build system is untenable. If the author is no longer maintaining it, we should consider moving off of it to something else, or building our own.

**Comment by jasongrout** [comment]
I also tried updating typedoc to 1.7 a few months ago. The current issue tracking updating typedoc is here: https://github.com/sebastian-lenz/typedoc/issues/162. There is at least one fork for typescript 1.7.5 (https://github.com/sebastian-lenz/typedoc/issues/162#issuecomment-199099058, I haven't tested it, though).

**Comment by jasongrout** [comment]
Also, at least one person is making another doc generator: https://github.com/sebastian-lenz/typedoc/issues/162#issuecomment-196161770.  Also, there has been issues in the typescript project for generating jsdoc annotations (and referencing how typedoc is falling behind): https://github.com/Microsoft/TypeScript/issues/10, https://github.com/Microsoft/TypeScript/issues/5595#issuecomment-163051163

**Comment by jasongrout** [comment]
When I was trying to update to ts 1.7, I got the impression that typedoc relies on internal implementation details of the compiler to get the typing information, and those details tend to break every major release, so porting the project can be a pain.

**Comment by sccolbert** [comment]
Yep. Typedoc relies on private APIs of the compiler, so it manually includes the compiler in the typedoc source through a hacky pre-build step. That's what I meant by "untenable" :). Ideally, a documentation tool would rely on the public typescript language service apis.

**Comment by jasongrout** [comment]
For reference, the docs can now build with https://github.com/TypeStrong/typedoc/pull/204, IIRC. Thanks, @blink1073!
