### ISSUE TITLE
Lab notebook doesn't create kernels

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyter-js-notebook#156]
This is a bug that was just mentioned today by @blink1073 on gitter. I hit it too, and with @Carreau's help I think we tracked it down to [this line](https://github.com/jupyter/jupyter-js-notebook/blob/1b9e7fcc125def3ae2d5e159b3d2c78950fb178c/src/notebook/selector.ts#L58) which is accessing `model.metadata.kernelspec` directly, while if I'm reading how [metadata is implemented](https://github.com/jupyter/jupyter-js-notebook/blob/1b9e7fcc125def3ae2d5e159b3d2c78950fb178c/src/notebook/model.ts#L599) correctly, can't work at all.  

HTH

**Comment by blink1073** [comment]
Thank you!  That is actually a new bug introduced during the metadata refactor.  We are in the process of fixing the original bug by allowing the notebook plugin to handle both notebook creation and opening, starting with https://github.com/jupyter/jupyter-js-ui/pull/46.

**Comment by blink1073** [comment]
Actually, there is no bug there, because we are setting default metadata on the model if none exists.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyter/jupyter-js-plugins/pull/151.
