### ISSUE TITLE
Add source maps in our webpack bundle

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter-js-notebook#160]
Right now debugging JupterLabs's frontend is essentially impossible because there are no source maps that allow you to navigate through the source code and find where the problem(s) are coming from. Looks like it is a simple option for webpack to include sourcemaps. Can we add that?

**Comment by ellisonbg** [comment]
I should emphasize that this is important for new developers who are coming to JupyterLab and don't already know the code base.

**Comment by blink1073** [comment]
Yep, I've opened PRs in all of the relevant places, thank you!

**Comment by blink1073** [comment]
Merged!

**Comment by Carreau** [comment]
Can we consider that closed by jupyter/notebook#1323 or is there more to do ?

**Comment by blink1073** [comment]
We also added it to `js-utils`, `js-notebook`, and `js-plugins`, so I believe we are covered.

**Comment by ellisonbg** [comment]
Great!

On Fri, Apr 8, 2016 at 9:29 AM, Steven Silvester notifications@github.com
wrote:

> We also added it to js-utils, js-notebook, and js-plugins, so I believe
> we are covered.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/issues/160#issuecomment-207503495

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by svenefftinge** [comment]
Should I see the typescript source in chrome? I only see the original js files that were bundled by webpack.

**Comment by blink1073** [comment]
Hi @svenefftinge, we are not source-mapping back to TypeScript in general.

**Comment by SylvainCorlay** [comment]
@svenefftinge notice that this repo is in the jupyter-attic organization. The maintained version of this code is in https://github.com/jupyter/jupyterlab
