### ISSUE TITLE
Clean up notebook models and make a controller

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#166]
- Basic notebook model would be everything needed to render a notebook.
- The interactive notebook model extends this and adds selected state handling and actions on the the model.
- Separate out code execution into a controller
- The toolbar will take no model and emit signals
- The toolbar should have an interface for adding and removing buttons

**Comment by blink1073** [comment]
Updated proposal for the models:

``` typescript

/**
 * The definition of a model object for a notebook.
 */
export
interface INotebookModel extends IDisposable {
  /**
   * A signal emitted when state of the notebook changes.
   */
  stateChanged: ISignal<INotebookModel, IChangedArgs<any>>;

  /**
   * A signal emitted when a user metadata state changes.
   */
  metadataChanged: ISignal<INotebookModel, string>;

  /**
   * The default mime type for new code cells in the notebook.
   *
   * #### Notes
   * This can be considered the default language of the notebook.
   */
  defaultMimetype: string;

  /**
   * Whether the notebook has unsaved changes.
   */
  dirty: boolean;

  /**
   * Whether the notebook is read-only.
   */
  readOnly: boolean;

  /**
   * The kernelspec metadata associated with the notebook.
   */
  kernelspec: IKernelspecMetadata;

  /**
   * The language info metadata associated with the notebook.
   */
  languageInfo: ILanguageInfoMetadata;

  /**
   * The original nbformat associated with the notebook.
   */
  origNbformat: number;

  /**
   * The list of cells in the notebook.
   *
   * #### Notes
   * This is a read-only property.
   */
  cells: IObservableList<ICellModel>;

  /**
   * A factory for creating a new code cell.
   *
   * @param source - The cell to use for the original source data.
   *
   * @returns A new code cell. If a source cell is provided, the
   *   new cell will be intialized with the data from the source.
   *
   * #### Notes
   * If the source argument does not give an input mimetype, the code cell
   * defaults to the notebook [[defaultMimetype]].
   */
  createCodeCell(source?: ICellModel): ICodeCellModel;

  /**
   * A factory for creating a new Markdown cell.
   *
   * @param source - The cell to use for the original source data.
   *
   * @returns A new markdown cell. If a source cell is provided, the
   *   new cell will be intialized with the data from the source.
   */
  createMarkdownCell(source?: ICellModel): IMarkdownCellModel;

  /**
   * A factory for creating a new raw cell.
   *
   * @param source - The cell to use for the original source data.
   *
   * @returns A new raw cell. If a source cell is provided, the
   *   new cell will be intialized with the data from the source.
   */
  createRawCell(source?: ICellModel): IRawCellModel;

  /**
   * Get a metadata cursor for the notebook.
   *
   * #### Notes
   * Metadata associated with the nbformat spec are set directly
   * on the model.  This method is used to interact with a namespaced
   * set of metadata on the notebook.
   */
  getMetadata(namespace: string): IMetadataCursor;

  /**
   * List the metadata namespace keys for the notebook.
   *
   * #### Notes
   * Metadata associated with the nbformat are not included.
   */
   listMetadata(): string[];
}


export
interface IInteractiveNotebookModel extends INotebookModel {
  /**
   * A signal emitted when the selection changes.
   */
  selectionChanged: ISignal<IInteractiveNotebookModel, void>;

  /**
   * The index of the active cell.
   */
  activeCellIndex: number;

  /**
   * The interactivity mode of the notebook.
   */
  mode: NotebookMode;

  /**
   * The kernel status of the notebook.
   *
   * #### Notes: This is a read-only property.
   */
  kernelStatus: kernelStatus;

  /**
   * Select a cell.
   */
  select(cell: ICellModel): void;

  /**
   * Deselect a cell.
   */
  deselect(cell: ICellModel): void;

  /**
   * Whether a cell is selected.
   */
  isSelected(cell: ICellModel): boolean;
}
```

**Comment by blink1073** [comment]
The session is completely removed from the model.  There will be a singleton `NotebookController` that maintains a copy/paste and delete/undelete stack shared across notebooks, as well as the session for each notebook.  

A toolbar item would take an `IInteractiveNotebookModel` and emit a `commandRequest(name: string)` signal with they name of command to execute on the `NotebookController`.

**Comment by blink1073** [comment]
ping @ellisonbg @jasongrout @minrk

**Comment by blink1073** [comment]
I couldn't see a way around having the toolbar item take a model.  It needs to know essentially everything about the notebook.  One option is to hand it read-only snapshot and then allow it to connect to a `changed` signal.

**Comment by blink1073** [comment]
``` typescript
/**
 * All attributes are read-only.
 */
interface IToolbarModel {
  stateChanged: ISignal<IToolbarModel, IChangedArgs<any>>;
  metadataChanged: ISignal<IToolbarModel, string>;
  selectionChanged: ISignal<IToolbarModel, void>;
  activeCellIndex: number;
  mode: NotebookMode;
  kernelStatus: kernelStatus;
  languageInfo: ILanguageInfoMetadata;
  kernelspec: IKernelspecMetadata;
  readOnly: boolean;
  dirty: boolean;
  defaultMimetype: string;
  getMetadata(namespace: string): IReadonlyMetadataCursor;
  listMetadata(): string[];
  requestCommand(name: string): void;
}
```

**Comment by blink1073** [comment]
We could also add `requestCommand(name: string): void` as a method of the toolbar item model (updated above).

**Comment by blink1073** [comment]
WIP diagram: https://drive.google.com/file/d/0B5VoDagiQzm-aGZxTG1nOG54VUU/view?usp=sharing

**Comment by jasongrout** [comment]
Thanks. I think we're getting there. One conceptual thing I realize about the toolbar from what you said above is that the toolbar has areas that provide a way to execute commands against the notebook _and_ render notebook state. In the case of the cell dropdown, it does both. So I agree that it makes sense for the toolbar to take a model and be able to invoke commands.

(Thinking out loud...) It seems a bit weird that the widgets can interact directly with the executor, but the toolbar can't. However, this is similar to the separation we have between providers and extensions in the application. Let's say you're running the notebook on a Raspberry Pi and you want a toolbar item that reflects the value of one of the ports on the board (maybe lets you set a corresponding value with a dropdown).  You should register both a plugin that can register a comm target and can maintain state, and a toolbar item that can render that state and effect change (not through a command, but through your plugin).

**Comment by blink1073** [comment]
Yes, this granularity of extension points and how they are registered and triggered is what I'd like to discuss.

**Comment by jasongrout** [comment]
I've been playing with another take on the diagram in that file (not sure if I'm editing a shared copy or my own copy, though...)

**Comment by jasongrout** [comment]
@blink1073 - Okay, I think I have a first iteration diagram up on the same document you shared above. I was going for: what is the absolute simplest system we can have, while maintaining the separation between execution and the model.

**Comment by blink1073** [comment]
Awesome, I think that is a great starting point.  @sccolbert wanted to discuss this architecture as well when you're ready.

**Comment by sccolbert** [comment]
Cool. Will take a look at those diagrams in a bit.

**Comment by sccolbert** [comment]
Looking at the diagram, but I need some more context. Can we setup a call?

**Comment by blink1073** [comment]
A thought: we could leave the list of cells as an observable list, but make them more opaque in that you can't reach in and directly change the input and output area.  The notebook itself would subscribe to changes on each of its cells.  Updates to the notebook come in the form of signals from the cells or direct method calls/property access on the notebook model.

**Comment by blink1073** [comment]
(And also changes to the observable list).

**Comment by blink1073** [comment]
Another thought: the session itself lives outside of the model, but the kernel does live on the model and we emit a signal when it changes.  We need a concrete handle on the kernel for things like registering comm targets and requesting code completion.

**Comment by jasongrout** [comment]
The model doesn't need to register comm targets, does it? Typically it seems that notebook plugins would be the ones to register comm targets, but they don't have to do it through the model.

We should design out the completions and who handles them.  Are completions metadata on a cell?

**Comment by blink1073** [comment]
Completions would be triggered by the user while typing in the codemirror cell.  Variable inspect could be done as a keyboard shortcut or a palette command.

**Comment by jasongrout** [comment]
Variable inspection could also be from a mouse hover, for example.

**Comment by blink1073** [comment]
Here is my attempt at making the third [flowchart](https://drive.google.com/file/d/0B5VoDagiQzm-aGZxTG1nOG54VUU/view?usp=sharing) more concrete:

``` typescript
// The widget associated with a notebook.
interface INotebookWidget {
  // The instance-specific rendermime registry.
  renderer: Renderer<Widget>;

  // The notebook model.
  model: INotebookModel;

  // The toolbar used to interact with the notebook.
  toolbar: INotebookToolbar;

  // The area used to render notebook content.
  contentArea: INotebookContentArea;
}


// The object used to interact with the notebook.
interface INotebookContext {
  // The widget associated with the notebook.
  widget: INotebookWidget;

  // The current kernel associated with the notebook.
  kernel: IKernel;

  // A signal emitted when the kernel changes.
  kernelChanged: ISignal<INotebookContext, IKernel>;

  // Change the kernel.
  changeKernel(kernel: IKernelId): Promise<IKernel>;

  // Save the contents of the notebook.
  save(): Promise<void>;

  // Push data to the application clipboard
  addToClipboard(bundle: MimeBundle): void;

  // Get the current application clipboard data.
  getClipboard(): MimeBundle;

  // Execute a commmand in the application by name.
  executeCommand(name: string): void;
}


// An instance of a notebook plugin.
interface INotebookPlugin {
  // Execute a command on the plugin by name.
  executeCommand(name: string): void;
}


// A notebook plugin factory.
interface INotebookPluginFactory {
  // The list of commands provided by the plugin.
  commands: string[];

  // Create a new plugin given a context.
  create(context: INotebookContext): INotebookPlugin;
}


// A registry for notebook plugins.
interface INotebookPluginRegistry {
  // Add a plugin to the registry.
  addPlugin(factory: INotebookPluginFactory): IDisposable;

  // A signal emitted when a plugin is added to the registry.
  pluginAdded: ISignal<INotebookPluginRegistry, void>;

  // Execute a command in a given context.
  executeCommand(name: string, context: INotebookContext): void;

  // The list of registered commands.
  commands: string[];

  // Create the plugin instances for a given context.
  create(context: INotebookContext): IDisposable;
}


// Creates notebook widgets and contexts and uses the registry to create the 
// plugins.
interface INotebookFileHandler {
  // Contents manager used to save/load notebook contents.
  contents: IContentsManager;

  // Manager used to create sessions.
  sessions: ISessionManager;

  // The global rendermime instance.
  renderer: RenderMime<Widget>;

  // The notebook plugin registry.
  plugins: INotebookPluginRegistry;

  // Execute a command on a given notebook path.
  executeCommand(name: string, path: string): void;
}


// Registers the commands from the plugin registry to phosphide.
// The command handlers find the current widget using the app shell API.
// If it is a notebook, execute the command on that notebook.
class NotebookTopLevelPlugin {
  filehandler: INotebookFileHandler;
}
```

**Comment by jasongrout** [comment]
Another way to simplify the model, but still incorporate kernel actions sort of on the model, is to attach a kernel object to the model using an attached property.

**Comment by blink1073** [comment]
Updates to sessions and kernel:
- The client side session object should not have a notebook path since it could become stale at any time
- If we have a path, we use the REST API to get a session model which may or may not create a new server side session
- Each client side kernel instance must have a unique client id to
  distinguish where the execution came from
- Kernel instances with a given kernel id share an object that manages
  the web socket - it emits a signal when it receives a valid message.
- Need to add an `iopubReceived` signal on the kernel instances that
  broadcasts all messages.
- Use the `unhandledMessage` signal only for non iopub messages that 
  match the clientId 

Ideas for execution:
- We have objects that can _be_ executed, and ones that can
  request execution.
- Objects that can be executed with have an execution context 
  with `kernel`, `kernelChanged`, and `changeKernel` interface.
- The document manager tracks the most recently focused widget
  that can be an execution target and applies a CSS class
- The document manager has an `execute(code: string)` method
  that will execute the code in the current execution target

**Comment by blink1073** [comment]
Using this model, a text file need not _have_ a kernel, but be able to execute code in the appropriate place, similar to how Matlab and RStudio function.

**Comment by jasongrout** [comment]
Some more design notes from a discussion with Steve:

There is a new DocumentManager service. It has functions to
- open a file, given a path, open mode (e.g., `'file'`, `'notebook'`), and a widget mode to determine which widget should be created
- create a model corresponding to a specific file contents for a specific file extension and mode
- create a new model for a specific file extension (and mode?)
- create a widget from a model. hands back a widget synchronousy (which may just be a placeholder widget which is later filled in)
- a way to register model and widget creators for various file types

The DocumentManager also has:
- map from filename/open mode to model
- map from model (and widget mode?) to list of widgets (maybe more than one), with one widget being a 'preferred' widget. The preferred widget is focused when trying to open a file that is already open.

The file browser depends on the document manager and in the case of dragging a file into the dock panel, calls the open file function which in turn calls the open model and create widget functions to synchronously return a widget which can be added to the dockpanel.

The generic model has a dispose signal, a serialize method.

How execution is handled is still under discussion. We think that:
- text files should _not_ have kernels associated with them. Only notebooks and consoles have kernels associated with them. Text files can send their text to a console, and the console can execute the code.

**Comment by jasongrout** [comment]
Update - a handler for a .py file _may_ have a kernel associated with it. Then you could implement LightTable/Hydrogen-like functionality in the text editor.

**Comment by blink1073** [comment]
That's fair.  And the semantics for selecting the _current_ execution target may also not be just focusing.

**Comment by jasongrout** [comment]
Right, good point.

**Comment by jasongrout** [comment]
Open question (for me, at least):  How does a file handler tell the document manager to attach a session? Or does it? Perhaps the document manager provides the file handler with a way to start a session, so that the handler can do whatever setup it wants of the session before handing back the model?

**Comment by blink1073** [comment]
True, the document manager could create the session context and hand it to the model creator.

**Comment by jasongrout** [comment]
But some models won't need a session. So perhaps the document manager can hand the model creator a sessionFactory.

**Comment by blink1073** [comment]
The session context doesn't necessarily denote a live session, it is just the `kernel/kernelChanged/changeKernel` interface.

**Comment by jasongrout** [comment]
Notes from our 2 May meeting

# 2 May 2016

## Context - for contents manager and execution
- save
- revert to disk
- checkpointing?
- kernel
- kernelChanged signal
- changeKernel(): Promise<IKernel>
- list of running sessions (which includes both a kernelspec and a filepath)

## IModel
- serialize/deserialize functions
- dispose function
- preferred kernel name
- preferred kernel language

## widgetFactory
- static method that takes a kernel spec list and filename and returns preferred kernel specs for the file and a default kernel. This is used to sort the options in the openWith and create dialogs.

## Document manager
- registerWidgetFactory('file type', displayedName, widgetFactory, modelName)
- registerDefaultWidgetFactory(same args as registerWidgetFactory)
- registerModelFactory(name, contentsOptions, modelFactory). contentsOptions: `{type: 'file' or 'notebook'; format: 'json', 'base64', 'text', undefined}`
- openWith('filename', parentwidget for dialog)
  - Creates dialog
    
    ```
    -------------------------------------------
      (readonly) Name: 2016-05-01-104521.ipynb
    
        Widget: Dropdown of registered widget factories for the file type
        Kernelspec: default (which means the widget or the server decides what to do with it). Also list running sessions.
    
                                      | OPEN |
    --------------------------------------------
    ```
  - Call open('filename', 'widget', kernel)
- open('filename', 'widget', kernel=None): synchronous, hands back container widget
  - The document manager finds out from the widgetFactory what modelFactory it should use. 
  - The document manager looks up the contents options to use for the modelFactory, and fetches the content. 
  - The document manager calls the modelFactory with the content synchronously get a model. The model exposes the default kernel/language.
  - Document manager creates a execution/contents context.
  - Call _createWidget and return container widget
- new(parentwidget for dialog): synchronous, hands back container widget
  - Create dialog
    
    ```
    -------------------------------------------
      Name: 2016-05-01-104521.ipynb
        | Python file | Text file | Jupyter Notebook | More v |
    
      Advanced v  
        Widget: Dropdown of registered widget factories for the file type
        Kernelspec: default (which means the widget or the server decides what to do with it). Also list running sessions.
    
                                      | CREATE |
    --------------------------------------------
    ```
  - GET rest api call to see if filename already exists. If filename conflict, then pop up a rename/overwrite dialog. We could also do this live as the user types the filename and show an error indicator or a list of matching filenames.
  - call modelFactory createNew static function (which is passed the kernel name and language). Get model back synchronously.
  - Save the blank model to disk (async).
  - Call _createWidget and return container widget
- _createWidget
  - Call widget with new model and a context and optional kernel to hook up to. Async returned widget is added to the container widget. The widget factory is responsible for starting a kernel if it wants one.
  - store `path->(model, session, context, [list,of,widgets])`
  - Hand back container widget synchronously
- rename('oldname', 'newname')
  - update any session
  - updates all container widget titles (possibly by calling a static method on the widgetFactory)
- delete('filename')
  - Look up kernel (if exists) and if this session is the only session using the kernel, ask user if they want to shut down the kernel.
  - dispose everything in the `path->(model, session, context, [list,of,widgets])` mapping for the path (disposing a session should not shut down the kernel - needs change in notebook server)
- I want to be able to drag an output area into a new tab panel. I want this to create a new sibling widget with my model and context. The document manager should be aware of this widget so that it doesn't become orphaned. Maybe the context has an extra method to add a widget to the document manager's `path->...` mapping.

**Comment by jasongrout** [comment]
@SylvainCorlay, @sccolbert, @ellisonbg - can we talk about the architecture in the previous comment tomorrow (Tuesday)? @blink1073 and I hashed this out for a while this afternoon, and would like to run it by you (and anyone else who wants to join in).

**Comment by blink1073** [comment]
I ran into a problem when trying to refactor `jupyter-js-services` to share a websocket connection for the kernel while keeping different client ids.  The client id is part of the websocket address itself and is expected by the [server](https://github.com/jupyter/notebook/blob/a4125572e4bb779f609b9400ea63a9dc09ffec15/notebook/base/zmqhandlers.py#L283).  Therefore, unless we change the server, we have to create a new `IKernel` with a new websocket for each client side consumer of a given kernel instance.

**Comment by jasongrout** [comment]
@blink1073: Wow. Okay, let's punt on that and create the new websocket for each client-side consumer. We were going to look into multiplexing all connections over one websocket in the future anyway.

**Comment by ellisonbg** [comment]
Thanks for pushing forward on this! Great to go over the design today.

On Tue, May 3, 2016 at 9:28 AM, Jason Grout notifications@github.com
wrote:

> @blink1073 https://github.com/blink1073: Wow. Okay, let's punt on that
> and create the new websocket for each client-side consumer. We were going
> to look into multiplexing all connections over one websocket in the future
> anyway.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jupyter/jupyter-js-notebook/issues/166#issuecomment-216585341

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
