### ISSUE TITLE
Add an execute method to the cells.

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#169]
RawCell and Markdown cell should just have `execute()`, while CodeCell has `execute(kernel)`.

**Comment by jasongrout** [comment]
Why must rawcell and markdown have an execute? A raw cell has no concept of execution. A markdown cell just renders client-side (it's not 'executed').

**Comment by blink1073** [comment]
Agreed, that's How I ended up implementing it
