### ISSUE TITLE
Blank screen on loading JupyterLab alpha from notebook master

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter-js-notebook#174]
@blink1073 @sccolbert Just a heads up (in case you didn't know already)

I'm getting a blank screen when I launch the JupyterLab alpha from the current Jupyter notebook master. Here are a couple of screenshots for troubleshooting:
<img width="1369" alt="screen shot 2016-04-13 at 10 03 07 am" src="https://cloud.githubusercontent.com/assets/2680980/14502276/5e87ebea-015f-11e6-8f7d-95cd31dc88b2.png">
<img width="922" alt="screen shot 2016-04-13 at 10 02 37 am" src="https://cloud.githubusercontent.com/assets/2680980/14502277/5e8f0556-015f-11e6-97c3-3cb32aab8a7e.png">
<img width="622" alt="screen shot 2016-04-13 at 10 01 29 am" src="https://cloud.githubusercontent.com/assets/2680980/14502289/69fb0de0-015f-11e6-9fcb-6ebaa4804c23.png">

**Comment by blink1073** [comment]
Thanks, @willingc.  I had made a mistake in `jupyter-js-ui` and released a patch instead of a minor release, I'm working on rectifying the mistake.

**Comment by blink1073** [comment]
Should be fixed now.  Can you verify by running `python setup.py js` and loading the lab page again?

**Comment by willingc** [comment]
Will do.

**Comment by sccolbert** [comment]
should probably blow away your `node_modules` first, just to be safe.

**Comment by blink1073** [comment]
To be clear: `notebook/notebook/lab/node_modules`.

**Comment by willingc** [comment]
Good tips.

<img width="1137" alt="screen shot 2016-04-13 at 11 02 17 am" src="https://cloud.githubusercontent.com/assets/2680980/14503947/56573d74-0167-11e6-8dd1-7ceec559613b.png">

**Comment by blink1073** [comment]
Ha!  Thanks @willingc.
