### ISSUE TITLE
Code cells in `command` mode should be rendered

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#200]
CodeMirror measures on window resizes, so having as few around as possible is good.

**Comment by blink1073** [comment]
See https://codemirror.net/demo/runmode.html for an example - generates `innerHTML` on a node:

```
import "codemirror/addon/runmode/runmode"
CodeMirror.runMode(myText, myMode, myNode);
```

**Comment by blink1073** [comment]
This should not be done automatically by the code cell, but available as `render/unrender` methods that can be used by a single-user notebook or a console, for example.

**Comment by afshin** [comment]
👍 

I agree. In the console, this is a no-brainer optimization.

**Comment by blink1073** [comment]
Moved to https://github.com/jupyter/jupyterlab/issues/15
