### ISSUE TITLE
Upcoming Tasks

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#211]
- [ ] Use new document manager and refactor models/views/controller
- [ ] Create a notebook extension registry and a `jupyter-js-widget` extension

**Comment by SylvainCorlay** [comment]
👍 

The custom widget libraries are probably going to be bundled slightly differently. Hence we probably don't need to rely on the same jupyter commands

`jupyter labextension [enable/install]...`

**Comment by blink1073** [comment]
@SylvainCorlay, extension is probably not the right word here.  These are basically JS classes that create a new instance of a _thing_ given an instance of a notebook widget.

**Comment by blink1073** [comment]
Implemented in jupyterlab.
