### ISSUE TITLE
Completion in notebook

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter-js-notebook#222]
Here are some things I observed with ffc042c06fb4470bc845b209b53f755be5f16b55 (from the cleanup PR).
- [x] tab completion didn't work from new code cell until I used it from an existing cell
- [x] tab completion worked from an existing markdown cell (should it?), but didn't seem to from a new markdown cell
- [x] completion list offset in cells past the first

![completion](https://cloud.githubusercontent.com/assets/192614/15655476/8ed3525e-266b-11e6-8efe-130bb224704e.gif)

**Comment by blink1073** [comment]
I also saw this bug:

<img width="273" alt="screen shot 2016-05-31 at 1 36 34 pm" src="https://cloud.githubusercontent.com/assets/2096628/15686184/c849839a-2734-11e6-88a6-e39615b732e5.png">

<img width="402" alt="screen shot 2016-05-31 at 1 36 41 pm" src="https://cloud.githubusercontent.com/assets/2096628/15686185/c98ed584-2734-11e6-92f4-8f94ce0805f1.png">

**Comment by blink1073** [comment]
This was after closing a notebook.

**Comment by blink1073** [comment]
Executing a cell currently makes the widget lose focus as well.

**Comment by afshin** [comment]
FYI, I am looking at these.

**Comment by afshin** [comment]
These issues and a few more are resolved in this PR: https://github.com/jupyter/jupyter-js-notebook/pull/225

**Comment by blink1073** [comment]
Calling this one fixed, thanks @afshin!
