### ISSUE TITLE
Cannot start console sample

### ISSUE THREAD

**Issue by DonJayamanne** [jupyter/jupyter-js-notebook#234]
Operating System: OS X
node v5.10.0
Python 3.5.2 :: Anaconda custom (x86_64)

I have installed the dependencies and created the build.
However when launching the console sample in the browser I get the following error:

```
POST http://localhost:8888/api/sessions?1473770830799 501 (Not Implemented)
session.js:752 API request failed (501):  Not ImplementedonSessionError @ session.js:752
bundle.js:5484 Uncaught (in promise) Error: Not Implemented(…)onSessionError @ session.js:753
```

Any help in this area would be much appreciated.

**Comment by blink1073** [comment]
Hi @DonJayamanne, this library is no longer maintained, and has moved jupyter/jupyterlab.  There is a console example there that is up to date.

**Comment by DonJayamanne** [comment]
@blink1073 , great thanks
