### ISSUE TITLE
Using different favicon's would make navigation easier [Was jupyter/jupyter 118]

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter-js-notebook#53]
Migrating an issue (https://github.com/jupyter/jupyter/issues/118) filed by @dubourg on the jupyter repo to here where it will be seen by more developers.

> Since we are tending toward a full OS in the browser... ;-) I think it would help to be able to differentiate the jupyter-js-filebrowser, jupyter-js-editor, jupyter-js-terminal and jupyter-js-notebook navigation tabs from the favicon.

**Comment by blink1073** [comment]
@dubourg, do you mean when that type of tab is active in JupyterLab?

**Comment by dubourg** [comment]
No, I was not aware of the jupyterlab project when I reported this. I was
simply suggesting this improvement for the current jupyter interface that
exposes the different jupyter apps in separated browser tabs.
Le 18 mars 2016 18:39, "Steven Silvester" notifications@github.com a
écrit :

**Comment by jasongrout** [comment]
Thanks. It looks like this issue really does belong on the jupyter/notebook repo. I migrated it to here: https://github.com/jupyter/notebook/issues/1254
