### ISSUE TITLE
Implement Notebook Cell Semantics

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#55]
Notes:
- [x] New cells are always code cells and are started in edit mode
- [x] Executing a cell selects the next cell but does not focus it
- [x] If the cell is not focused, we are in command mode
- [x] Cells can be executed in command mode
- [x] A cell can be: selected, focused, and marked, each of which has a different semantic meaning
- [x] Rendering an empty markdown cell should display a message:
  Type Markdown and LaTeX:  α^2

**Comment by blink1073** [comment]
cc @jasongrout @Carreau @ellisonbg

**Comment by blink1073** [comment]
cc @minrk

**Comment by Carreau** [comment]
> Executing a cell selects the next cell but does not focus it

that's only with the keyboard. Ctrl-Enter execute and select same cell. 

The text in empty markdown cell is not that strict as long as it guide users IMHO.

**Comment by minrk** [comment]
Yup, I think that's the gist. As @Carreau mentioned, the exact placeholder text isn't important. It's mainly there to keep a rendered, empty markdown cell from being invisible.
