### ISSUE TITLE
Add katex fallback mode for markdown cells

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-notebook#58]

**Comment by jasongrout** [comment]
I think https://github.com/jupyter/jupyter-js-notebook/pull/119 fixes this by moving the katex fallback into the typeset utility function.

**Comment by blink1073** [comment]
Katex also requires some CSS.

**Comment by blink1073** [comment]
We've decided to not do this, and instead allow `katex` to be provided as a plugin if desired.
